"""empty message

Revision ID: a6af0d7748ea
Revises: ed5a31608d36
Create Date: 2025-10-27 21:11:55.558896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6af0d7748ea'
down_revision = 'ed5a31608d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_parent_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['parent_post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_parent_post_id_fkey'), 'posts', ['parent_post_id'], ['id'])

    # ### end Alembic commands ###
