"""empty message

Revision ID: afe9a8adb56e
Revises: ef19c8b18b82
Create Date: 2025-10-27 22:02:22.347742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe9a8adb56e'
down_revision = 'ef19c8b18b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted_parent_post', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted_parent_post')

    # ### end Alembic commands ###
