"""Add constraints to subscribers table

Revision ID: ce5cfc6df5d4
Revises: ecf003005299
Create Date: 2025-10-02 21:33:23.067312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5cfc6df5d4'
down_revision = 'ecf003005299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_subscription', ['user_id', 'user_id_subscriber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_subscription', type_='unique')

    # ### end Alembic commands ###
