"""empty message

Revision ID: ecf003005299
Revises: 0d86c2ee17da
Create Date: 2025-10-02 20:21:47.641139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf003005299'
down_revision = '0d86c2ee17da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_subscriber', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id_subscriber'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id_subscriber')

    # ### end Alembic commands ###
