"""empty message

Revision ID: ed5a31608d36
Revises: 18f8828e156f
Create Date: 2025-10-27 21:02:48.074741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5a31608d36'
down_revision = '18f8828e156f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_comments_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_favourites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_favourites_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_likes_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_likes_post_id_fkey'), 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('post_favourites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_favourites_post_id_fkey'), 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_comments_post_id_fkey'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
